services:
  - type: web
    name: premier-brushworks-jobhub
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run pb_jobhub_app.py --server.address 0.0.0.0 --server.port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.4
      - key: DATABASE_URL
        sync: false
