[server]
headless = true
maxUploadSize = 750
fileWatcherType = "none"
runOnSave = false
enableStaticServing = true

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#8A6B4B"
backgroundColor = "#F9F6F1"
secondaryBackgroundColor = "#F0E7DC"
textColor = "#2B2520"
